# docker-compose.yml
version: '3'
services:
  hrapp:
    image: "humanresources:4.0"
    ports:
      - "9000:9000"
    depends_on:
      - database

  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose